### ISSUE TITLE
dfs prompt returns an error

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairOS-dfs#1]
```
$ ./dist/dfs prompt

  /$$$$$$          /$$            /$$$$$$   /$$$$$$                /$$  /$$$$$$         
 /$$__  $$        |__/           /$$__  $$ /$$__  $$              | $$ /$$__  $$        
| $$  \__//$$$$$$  /$$  /$$$$$$ | $$  \ $$| $$  \__/          /$$$$$$$| $$  \__//$$$$$$$
| $$$$   |____  $$| $$ /$$__  $$| $$  | $$|  $$$$$$  /$$$$$$ /$$__  $$| $$$$   /$$_____/
| $$_/    /$$$$$$$| $$| $$  \__/| $$  | $$ \____  $$|______/| $$  | $$| $$_/  |  $$$$$$ 
| $$     /$$__  $$| $$| $$      | $$  | $$ /$$  \ $$        | $$  | $$| $$     \____  $$
| $$    |  $$$$$$$| $$| $$      |  $$$$$$/|  $$$$$$/        |  $$$$$$$| $$     /$$$$$$$/
|__/     \_______/|__/|__/       \______/  \______/          \_______/|__/    |_______/


panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x9df12e]

goroutine 1 [running]:
github.com/fairdatasociety/fairOS-dfs/cmd/dfs/cmd.glob..func1(0x1044680, 0x10c0dd8, 0x0, 0x0)
	/home/crtah/Documents/FairDataSociety/fairOS-dfs/cmd/dfs/cmd/prompt.go:61 +0xae
github.com/spf13/cobra.(*Command).execute(0x1044680, 0x10c0dd8, 0x0, 0x0, 0x1044680, 0x10c0dd8)
	/home/crtah/Documents/FairDataSociety/fairOS-dfs/vendor/github.com/spf13/cobra/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x1044920, 0xc0000b4008, 0xc000267f58, 0x1)
	/home/crtah/Documents/FairDataSociety/fairOS-dfs/vendor/github.com/spf13/cobra/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/crtah/Documents/FairDataSociety/fairOS-dfs/vendor/github.com/spf13/cobra/command.go:887
github.com/fairdatasociety/fairOS-dfs/cmd/dfs/cmd.Execute()
	/home/crtah/Documents/FairDataSociety/fairOS-dfs/cmd/dfs/cmd/root.go:65 +0xa5
main.main()
	/home/crtah/Documents/FairDataSociety/fairOS-dfs/cmd/dfs/main.go:24 +0x25


```

**Comment by jmozah** [comment]
Fixed in PR  https://github.com/fairDataSociety/fairOS-dfs/pull/2
