### ISSUE TITLE
API method doc/loadjson crashing the server

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairOS-dfs#102]
1 - Create new doc with `doc/new` and si param `first_name=string,age=number`
2 - Call `doc/loadjson` with data `[{"first_name": "Hello", "age": 11}]`

Get error
```
time="2021-08-13T08:35:32Z" level=info msg="creeating batch for inserting in document db: my_doc"
time="2021-08-13T08:35:32Z" level=info msg="finding from document db: my_doc1"
time="2021-08-13T08:35:32Z" level=info msg="loading Manifest: 326d58ceafd8my_docid"
time="2021-08-13T08:35:32Z" level=info msg="created simple batch index: id"
time="2021-08-13T08:35:32Z" level=info msg="created simple batch index: first_name"
time="2021-08-13T08:35:32Z" level=info msg="created simple batch index: age"
time="2021-08-13T08:35:32Z" level=info msg="created batch for inserting in document db: my_doc"
2021/08/13 08:35:32 http: panic serving 192.168.100.6:55848: interface conversion: interface {} is []interface {}, not map[string]interface {}
goroutine 603 [running]:
net/http.(*conn).serve.func1(0x206ab40)
        net/http/server.go:1804 +0x104
panic(0x7414e8, 0x1c291b8)
        runtime/panic.go:971 +0x4b4
github.com/fairdatasociety/fairOS-dfs/pkg/collection.(*Document).DocBatchPut(0x1f77d40, 0x1c11970, 0x1e81b30, 0x24, 0x30, 0x0, 0x0, 0x0, 0x0)
        github.com/fairdatasociety/fairOS-dfs/pkg/collection/document.go:1075 +0x1dcc
github.com/fairdatasociety/fairOS-dfs/pkg/dfs.(*DfsAPI).DocBatchPut(0x1f140c0, 0x1d68e10, 0x2c, 0x1c2f2f0, 0xc, 0x1e81b30, 0x24, 0x30, 0x1c11970, 0x0, ...)
        github.com/fairdatasociety/fairOS-dfs/pkg/dfs/doc_api.go:255 +0xe4
github.com/fairdatasociety/fairOS-dfs/pkg/api.(*Handler).DocLoadJsonHandler(0x1f26070, 0xa184e4, 0x1d82dc8, 0x2146b80)
        github.com/fairdatasociety/fairOS-dfs/pkg/api/doc_loadjson.go:112 +0x5ac
net/http.HandlerFunc.ServeHTTP(0x1f089e0, 0xa184e4, 0x1d82dc8, 0x2146b80)
        net/http/server.go:2049 +0x34
github.com/fairdatasociety/fairOS-dfs/pkg/api.(*Handler).LoginMiddleware.func1(0xa184e4, 0x1d82dc8, 0x2146b80)
        github.com/fairdatasociety/fairOS-dfs/pkg/api/login_middleware.go:54 +0x25c
net/http.HandlerFunc.ServeHTTP(0x212b240, 0xa184e4, 0x1d82dc8, 0x2146b80)
        net/http/server.go:2049 +0x34
github.com/fairdatasociety/fairOS-dfs/pkg/api.(*Handler).LogMiddleware.func1(0xa18c00, 0x21ea280, 0x2146b80)
        github.com/fairdatasociety/fairOS-dfs/pkg/api/log_middleware.go:34 +0xac
net/http.HandlerFunc.ServeHTTP(0x212b250, 0xa18c00, 0x21ea280, 0x2146b80)
        net/http/server.go:2049 +0x34
github.com/gorilla/mux.(*Router).ServeHTTP(0x1f22060, 0xa18c00, 0x21ea280, 0x2146a80)
        github.com/gorilla/mux@v1.7.4/mux.go:210 +0x98
github.com/rs/cors.(*Cors).Handler.func1(0xa18c00, 0x21ea280, 0x2146a80)
        github.com/rs/cors@v1.7.0/cors.go:219 +0x170
net/http.HandlerFunc.ServeHTTP(0x1f27420, 0xa18c00, 0x21ea280, 0x2146a80)
        net/http/server.go:2049 +0x34
net/http.serverHandler.ServeHTTP(0x1f4c120, 0xa18c00, 0x21ea280, 0x2146a80)
        net/http/server.go:2867 +0x88
net/http.(*conn).serve(0x206ab40, 0xa195fc, 0x2142ee0)
        net/http/server.go:1932 +0x7f0
created by net/http.(*Server).Serve
        net/http/server.go:2993 +0x318
```

**Comment by asabya** [comment]
`loadjson` only tries to read one json object rather than an array of json objects.

**Comment by tfius** [comment]
@asabya do we have a test for this ? 
This is done with BigQuery in mind (check https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-json)
so each line in json is an object that will be inserted into doc db.
