### ISSUE TITLE
FairOS crashing with Github Actions and fdp-play

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairOS-dfs#257]
**Describe the bug**
FairOS crashing with Github Actions and fdp-play

**To Reproduce**
1) Fork https://github.com/fairDataSociety/fdp-storage/tree/feat-108-integration-test-fairos
2) Make some changes in a new branch for `feat-108-integration-test-fairos` and create a pull request with these changes. To see a log with error necessary to replace `fdp-play start -d --fairos --bee-version $BEE_VERSION` to `fdp-play start --fairos --bee-version $BEE_VERSION`.
3) It triggers Github Workflow which will fail.

**Expected behavior**
FairOS works and expose 9090 port

**Error logs**

```
- Spawning network...
✔ Network is up
- Getting blockchain image version...
✔ Blockchain node is up and listening
- Starting queen Bee node...
✔ Queen node is up and listening
- Starting worker Bee nodes...
✔ Worker nodes are up and listening
- Starting FairOS node...
✔ FairOS node is up and listening

Y  /$$$$$$          /$$            /$$$$$$   /$$$$$$                /$$  /$$$$$$         
Y /$$__  $$        |__/           /$$__  $$ /$$__  $$              | $$ /$$__  $$        
Y| $$  \__//$$$$$$  /$$  /$$$$$$ | $$  \ $$| $$  \__/          /$$$$$$$| $$  \__//$$$$$$$
Y| $$$$   |____  $$| $$ /$$__  $$| $$  | $$|  $$$$$$  /$$$$$$ /$$__  $$| $$$$   /$$_____/
Y| $$_/    /$$$$$$$| $$| $$  \__/| $$  | $$ \____  $$|______/| $$  | $$| $$_/  |  $$$$$$ 
Y| $$     /$$__  $$| $$| $$      | $$  | $$ /$$  \ $$        | $$  | $$| $$     \____  $$
Y| $$    |  $$$$$$$| $$| $$      |  $$$$$$/|  $$$$$$/        |  $$$$$$$| $$     /$$$$$$$/
X|__/     \_______/|__/|__/       \______/  \______/          \_______/|__/    |_______/
Btime="2022-09-07T14:07:[5](https://github.com/IgorShadurin/fdp-storage-temp/runs/8229900442?check_suite_focus=true#step:6:6)8Z" level=info msg="configuration values"
Ptime="2022-09-07T14:07:58Z" level=info msg="version        : 0.8.2-rc[6](https://github.com/IgorShadurin/fdp-storage-temp/runs/8229900442?check_suite_focus=true#step:6:7)-065ed98"
Ctime="2022-09-0[7](https://github.com/IgorShadurin/fdp-storage-temp/runs/8229900442?check_suite_focus=true#step:6:8)T14:07:5[8](https://github.com/IgorShadurin/fdp-storage-temp/runs/8229900442?check_suite_focus=true#step:6:9)Z" level=info msg="network        : play"
Ytime="2022-0[9](https://github.com/IgorShadurin/fdp-storage-temp/runs/8229900442?check_suite_focus=true#step:6:10)-07T14:07:58Z" level=info msg="beeApi         : http://fdp-play-queen:1633"
Dtime="2022-09-07T14:07:58Z" level=info msg="isGatewayProxy : false"
Dtime="2022-09-07T14:07:58Z" level=info msg="verbosity      : trace"
Dtime="2022-09-07T14:07:58Z" level=info msg="httpPort       : :9090"
Dtime="2022-09-07T14:07:58Z" level=info msg="pprofPort      : :9091"
Htime="2022-09-07T14:07:58Z" level=info msg="cookieDomain   : localhost"
time="2022-09-07T14:07:58Z" level=info msg="postageBlockId : 7a1b20653f48ddd878276cb3d69d71c0724dd23b79abef345c386a62cbebfbac"
Btime="2022-09-07T14:07:58Z" level=info msg="corsOrigins    : [*]"
dtime="2022-09-07T14:07:59Z" level=info msg="ensProviderBackend   : http://fdp-play-blockchain:9545"
Htime="2022-09-07T14:07:59Z" level=info msg="ensProviderDomain    : fds"
ptime="2022-09-07T14:07:59Z" level=info msg="ENSRegistryAddress    : 0x26b4AFb60d6C903165150C6F0AA14F8016bE4aec"
qtime="2022-09-07T14:07:59Z" level=info msg="FDSRegistrarAddress    : 0x630589690929E9cdEFDeF0734717a9eF3Ec7Fcfe"
stime="2022-09-07T14:07:59Z" level=info msg="PublicResolverAddress    : 0xA94B7f0465E98609391C623d0560C5720a3f2D33"
8fatal error: unexpected signal during runtime execution
N[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7fc890281298]

runtime stack:
,runtime.throw({0xc5f471?, 0x7fc86c000d53?})
M	runtime/panic.go:[10](https://github.com/IgorShadurin/fdp-storage-temp/runs/8229900442?check_suite_focus=true#step:6:11)47 +0x5d fp=0x7fc88bffe830 sp=0x7fc88bffe800 pc=0x4396bd
runtime.sigpanic()
S	runtime/signal_unix.go:819 +0x369 fp=0x7fc88bffe880 sp=0x7fc88bffe830 pc=0x44fd69

goroutine 27 [syscall]:
(runtime.cgocall(0xa59f90, 0xc000044d98)
J	runtime/select.go:328 +0x7bc fp=0xc000055ed0 sp=0xc000055d90 pc=0x44c07c
0net/http.(*persistConn).writeLoop(0xc000477440)
N	net/http/transport.go:2392 +0xf5 fp=0xc000055fc8 sp=0xc000055ed0 pc=0x7174f5
'net/http.(*Transport).dialConn.func6()
N	net/http/transport.go:1752 +0x26 fp=0xc000055fe0 sp=0xc000055fc8 pc=0x7[13](https://github.com/IgorShadurin/fdp-storage-temp/runs/8229900442?check_suite_focus=true#step:6:14)fe6
runtime.goexit()
K	runtime/asm_amd64.s:[15](https://github.com/IgorShadurin/fdp-storage-temp/runs/8229900442?check_suite_focus=true#step:6:16)94 +0x1 fp=0xc000055fe8 sp=0xc000055fe0 pc=0x46d021
*created by net/http.(*Transport).dialConn
$	net/http/transport.go:[17](https://github.com/IgorShadurin/fdp-storage-temp/runs/8229900442?check_suite_focus=true#step:6:18)52 +0x1791
```

Full logs here: https://github.com/IgorShadurin/fdp-storage-temp/runs/8229900442?check_suite_focus=true
Github workflow: https://github.com/IgorShadurin/fdp-storage-temp/blob/IgorShadurin-patch-5/.github/workflows/tests.yaml

**Comment by asabya** [comment]
Does it happen if `fdp-play` is run stand alone or only in gh-action?

**Comment by IgorShadurin** [comment]
> only in gh-action

Yes, only in gh-action

**Comment by asabya** [comment]
The panic comes form go standard lib, not much to do on fairOS side. 

Most likely DNS lookup fails for the endpoints `http://fdp-play-queen:1633` and `http://fdp-play-blockchain:9545`. How is the network setup in fdp-play? can we add the local domain names into `/etc/hosts` or sth? 

Or maybe we try with localhost?

**Comment by asabya** [comment]
Not related to DNS. v0.8.2-rc5 runs fine on gh-action . But fails for v0.8.2-rc6 as it is built goreleaser with CGO_ENABLED.

The error is also related to that. May be it is missing some dependencies.

**Comment by asabya** [comment]
@IgorShadurin Please complete the tests with tag `v0.8.2-rc5`.

**Comment by asabya** [comment]
Tests are passing now https://github.com/fairDataSociety/fdp-storage/pull/148. There is no requirement of change in the workflow. fairOS-dfs Docker image has been updated to v0.8.2-rc7 with the fix.
